// app/layout.tsx
import type { Metadata } from "next";
import { Outfit, Poppins } from "next/font/google";
import "./globals.css";
import "@/styles/main.css";
import "@/styles/style.css";
import HeadTop from "@/utils/headTop";
import { getSettings, Settings } from "@/myapi/apiData/settings";
import VisitorsRecord from "@/myapi/visitorsRecord";
import { Providers } from "./providers";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings: Settings = await getSettings();

  return (
    <html lang="en">
      <body className={`${outfit.className} ${poppins.variable} antialiased`}>
        <Providers>
          {settings.visitorTracking === 1 && <VisitorsRecord />}
          <HeadTop settings={settings} />
          {children}
        </Providers>
      </body>
    </html>
  );
}