

import type { Metadata } from "next";
import { Outfit, Poppins } from "next/font/google";
import "./globals.css";
import "@/styles/main.css";
import "@/styles/style.css";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit", 
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${poppins.variable} antialiased`}> 
        {children}
      </body>
    </html>
  );
}